#!/bin/bash

set -e
cd `dirname $0`
cd .. # .codapt
cd .. # project root

# get the port from the .env file
source .env

# ensure port is set
if [ -z "$PORT" ]; then
  echo "PORT is not set, exiting..."
  exit 1
fi

# check if the app is running
curl -s -o /dev/null -w "%{http_code}" http://localhost:$PORT/nonexistent | grep -q "404"
if [ $? -ne 0 ]; then
  echo "App is not running, exiting..."
  exit 1
fi

echo "App is running"
